import dotenv from 'dotenv'

dotenv.config()

const {
  ENABLED_QUEUE_DIRECTORIES,
  TEST_SAFE_MAILING_LIST_ADDRESSES,
} = process.env

export default {
  ...process.env,
  ENABLED_QUEUE_DIRECTORIES: ENABLED_QUEUE_DIRECTORIES ? ENABLED_QUEUE_DIRECTORIES.split(',') : '',
  TEST_SAFE_MAILING_LIST_ADDRESSES: TEST_SAFE_MAILING_LIST_ADDRESSES ? TEST_SAFE_MAILING_LIST_ADDRESSES.split(',') : '',
}
